spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/db_users
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
name : Hello!
user :
 userName : this is
